#!/usr/bin/env zsh
msg=$1

if [ -z "$msg" ]; then
  echo message required > /dev/stderr
  exit 1
fi

rel_path() {
    local common path up
    common=${1%/} path=${2%/}/
    while test "${path#"$common"/}" = "$path"; do
        common=${common%/*} up=../$up
    done
    path=$up${path#"$common"/}; path=${path%/}; printf %s "${path:-.}"
}
org_dir=$(rel_path $HOME/dev $PWD | sed 's/\/.*//')
CUR_ENV=$(cat $ENV_FILE)


if ! test -d .git ; then
  echo "You are not in a git repository" > /dev/stderr
  exit 1
fi
if [[ $PWD/ == $HOME/dev/* ]]; then
  if [[ $PWD/ != $HOME/dev/$CUR_ENV/* ]]; then
    echo 'It looks like you are in the wrong environment for your project.' > /dev/stderr
    echo > /dev/stderr
    echo "Current environment: $CUR_ENV" > /dev/stderr
    echo "Suggested environment: $org_dir" > /dev/stderr

    echo -n 'Switch to `'$org_dir'` (Y/n)? ' > /dev/stderr
    read answer
    echo $answer
    if [[ "$answer" == *y* ]] || [[ "$answer" == *Y* ]]; then
      source $HOME/.zshrc
      set_env $org_dir
    fi
  fi
else
  echo -n 'It looks like you are outside a project ('$CUR_ENV'). Continue (Y/n)? ' > /dev/stderr
  read answer
  if [[ "$answer" != *y* ]] && [[ "$answer" != *Y* ]]; then
    exit 1
  fi
fi

git add . -A
git commit -m "$msg"
git push

