#!/bin/bash

gh alias set rcl "repo clone"
gh alias set rcr "repo create"
gh alias set rfk "repo fork --clone --remote"
gh alias set rv "repo view"
gh alias set rvw "repo view --web"
gh alias set icl "issue close"
gh alias set icr "issue create"
gh alias set il "issue list"
gh alias set ire "issue reopen"
gh alias set iv "issue view"
gh alias set ivw "issue view --web"
gh alias set pco "pr checkout"
gh alias set pck "pr checks"
gh alias set pcl "pr close"
gh alias set pcr "pr create"
gh alias set pd "pr diff"
gh alias set pl "pr list"
gh alias set pm "pr merge"
gh alias set pre "pr reopen"
gh alias set pv "pr view"
gh alias set pvw "pr view --web"
