#!/bin/bash

REPO=stedolan/jq

VERSION=jq-$(gh release list -R https://github.com/$REPO | grep Latest | awk '{ print $2 }')
ARCH=$(uname -m)
if [ $ARCH == x86_64 ]; then
  ARCH=amd64
fi
PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ $PLATFORM == darwin ]; then
  PLATFORM=osx
fi
BINARY=jq-${PLATFORM}-${ARCH}
curl -L -O https://github.com/$REPO/releases/download/${VERSION}/${BINARY}
if [ $? == 0 ]; then
  echo Not found > /dev/stderr
  exit 1
fi

chmod +x ${BINARY}
sudo mv ${BINARY} /usr/local/bin/jq