#!/bin/bash

REPO=stedolan/jq

VERSION=$(gh release list -R https://github.com/$REPO | grep Latest | awk '{ print $1 }')
ARCH=$(uname -m)
if [ $ARCH == x86_64 ]; then
  ARCH=amd64
fi
PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ $PLATFORM == darwin ]; then
  PLATFORM=osx
fi
BINARY=jq-${PLATFORM}-${ARCH}

curl -L -O https://github.com/$REPO/releases/download/${VERSION}/${BINARY}
chmod +x ${BINARY}
sudo mv ${BINARY} /usr/local/bin/jq