#!/bin/bash

REPO=digitalocean/doctl

RELEASE=$(latest_release ${REPO})
ARCH=$(get_arch)
PLATFORM=$(get_platform)
BINARY=doctl-${RELEASE}-${PLATFORM}-${ARCH}

curl -L https://github.com/${REPO}/releases/download/${RELEASE}/${BINARY}.tar.gz | tar xzf
chmod +x ${BINARY}
sudo mv ${BINARY} /usr/local/bin/doctl