#!/bin/bash

project_status() {
  ENV=$(cat $ENV_FILE)
  projects=$(find -L $DEV_DIR/$ENV  -type d -name '.git')
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  NC='\033[0m' # No Color
  for proj in ${projects}; do
    echo -n $(dirname ${proj:$((${#DEV_DIR}+1))})
    if (cd $proj/..; test -z "$(git status -s)") ; then
      echo -e "${GREEN} ✓${NC}"
    else
      echo -e "${RED} x${NC}"
    fi
    echo
  done
}
echo Environment: $(cat $ENV_FILE)
echo Projects:
column -t <<< $(project_status) | sed 's/^/  /'
echo Recent Projects:
cat $DEV_HIST  | awk '!x[$0]++' | tail -n 3 | sed 's/^/  /'
