#!/bin/bash

ENV=$(cat $ENV_FILE)

all_project_status() {
  projects=$(find -L $DEV_DIR/$ENV  -type d -name '.git')
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  NC='\033[0m' # No Color
  for proj in ${projects}; do
    echo -n $(dirname ${proj:$((${#DEV_DIR}+1))})
    if (cd $proj/..; test -z "$(git status -s)") ; then
      echo -e "${GREEN} ✓${NC}"
    else
      echo -e "${RED} x${NC}"
    fi
    echo
  done
}

status_all() {
  echo Environment: $ENV
  echo Projects:
  column -t <<< $(all_project_status) | sed 's/^/  /'
  echo Recent Projects:
  cat $DEV_HIST  | awk '!x[$0]++' | tail -n 3 | sed 's/^/  /'
}

status_one() {
  local project=$1
  if [ $project != "." ]; then
    cd $DEV_DIR/$ENV/$project
  fi
  for f in $(git ls-files --others --exclude-standard -z); do
    git add -N $f
  done
  git diff
}

if [ -z $1 ]; then
  status_all
else
  status_one $@
fi
