#!/bin/bash

HOSTS_FILE="/etc/hosts"
ADDED_TEXT_SUFFIX=_admin
ADDED_START_TEXT="# Start of section $USER$ADDED_TEXT_SUFFIX"
ADDED_END_TEXT="# End of section $USER$ADDED_TEXT_SUFFIX"

prev_start_line_no=$(grep -n "$ADDED_START_TEXT" "$HOSTS_FILE" | cut -d: -f1 | head -n 1)
prev_end_line_no=$(grep -n "$ADDED_END_TEXT" "$HOSTS_FILE" | cut -d: -f1 | head -n 1)

new_hostnames=`doctl compute droplet list --format "PublicIPv4,Name" | tail -n +2`

err_msg() {
  echo "$1" >/dev/stderr
}

append_hosts() {
  echo "$1" | sudo tee -a $HOSTS_FILE
}

delete_old() {
  if [ -n "$prev_start_line_no" ]; then
    if [ -z "$prev_end_line_no" ]; then
      err_msg "Error: found start of hosts with '$ADDED_START_TEXT' at line $prev_start_line_no,"
      err_msg "but did not find end, '$ADDED_END_TEXT' in $HOSTS_FILE."
      err_msg "Please edit $HOSTS_FILE manually."
      exit 1
    fi

    echo "Found existing host names at lines $prev_start_line_no-$prev_end_line_no:"
    sed -n "$prev_start_line_no,/$prev_end_line_no/"p $HOSTS_FILE

    echo "Deleting previous host names."
    sed -e "$prev_start_line_no,$prev_end_line_no"d $HOSTS_FILE | sudo tee $HOSTS_FILE
  else
    echo "Original hostnames not found. Just appending."
  fi
}

add_new() {
  echo
  echo "Appending new host names to $HOSTS_FILE:"
  echo "$new_hostnames"
  echo
  append_hosts "$ADDED_START_TEXT"
  append_hosts "$new_hostnames"
  append_hosts "$ADDED_END_TEXT"
  echo "Succesfully appended hostnames."
}

delete_old
add_new
