#!/bin/bash

set -eux

if [ -z "$1" ]; then echo Must provide image, e.g. ext4.img > /dev/stderr; exit 1; fi

umount /tmp/mounted
IFS=':' dev=$(losetup -a | grep $1 | awk '{ print $1 }')
losetup -d $dev