#!/usr/bin/env bash

# output all projects in order of most recently used

relpath() {
  local p1=$1
  local p2=$2
  echo $(dirname ${p2:$((${#p1}+1))}) 
}

output_all() {
  local projects=$(find -L $DEV_DIR/$ENV  -type d -name '.git')
  for project in $projects; do
    relpath $DEV_DIR $project
  done
}


filter_deleted() {
  local in;
  while read in; do
    test -d "$DEV_DIR/$in/.git" && echo "$in"
  done
}

touch $DEV_HIST

ENV=$(cat $ENV_FILE)
cat <(tac $DEV_HIST) <(output_all) | awk '!x[$0]++' | sed 's/^/  /' | head -n 10 | filter_deleted
