#!/usr/bin/env bash

strip_DEVDIR() {
  local my_path=$(realpath $1)
  [[ $my_path/* == $DEVDIR/* ]] && echo ${my_path:$((${#DEVDIR}+1))} && return 0
  return 1
}

# output all projects in order of most recently used
relpath() {
  local p1=$1
  local p2=$2
  echo $(dirname ${p2:$((${#p1}+1))})
}

output_all() {
  local projects=$(find -L $DEVDIR/$ENV -type d -name '.git')
  for project in $projects; do
    strip_DEVDIR $project
  done
}


filter_deleted() {
  local in;
  while read in; do
    test -r "$DEVDIR/$in/.git" && [ -n "$in" ] && echo "$in"
  done
}

touch $DEV_HIST

cat <(tac $DEV_HIST) <(output_all) | awk '!x[$0]++' | sed 's/^/  /' | head -n 10 | filter_deleted
